#stage-1
FROM node:18-alpine AS backend-builder
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . .

#stage-2
FROM node:18-alpine
WORKDIR /app
COPY --from=backend-builder /app .        
COPY .env.local .env
EXPOSE 3000
CMD ["npm", "run", "dev"]