#stage-1
FROM node:20-alpine AS backend-builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .

#stage-2
FROM node:20-alpine
WORKDIR /app
COPY --from=backend-builder /app ./
COPY .env.local .env
EXPOSE 3000
CMD ["node", "server.js"]